apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: device-model
  namespace: default
spec:
  properties:
    - name: version
      type:
        string:
          accessMode: ReadWrite
          defaultValue: ''
    - name: file_md5
      type:
        string:
          accessMode: ReadWrite
          defaultValue: ''
